import cors from "cors";
import express from "express";
import authRouter from "./routers/auth";
import roleRouter from "./routers/role";
import contactRouter from "./routers/contact";
import aboutRouter from "./routers/about";
import newsRouter from "./routers/news";
import reviewRouter from "./routers/reviews";
import userRouter from "./routers/User";
import imageRouter from "./routers/uploadImage";
import statusOrderRouter from "./routers/stauts_order";
import category from "./routers/category";
import products from "./routers/products";
import order from "./routers/order";
import dashboardRoutes from "./routers/dashboard";
import bannerRouter from "./routers/banner";
import PrintInvoice from "./routers/PrintInvoice";
import websiteInformationRoutes from "./routers/websiteInformation";
import paymentMethodsRoutes from "./routers/paymentMethods";
import deliveryAddressRoutes from "./routers/deliveryAddress";
import statusPaymentRouters from "./routers/statusPayment";
import footerRouters from "./routers/footer";
import messageRouter from "./routers/message";
const app = express();
app.use(express.json());
app.use(cors());

app.use("/api", messageRouter);
app.use("/api", bannerRouter);
app.use("/api", authRouter);
app.use("/api", roleRouter);
app.use("/api", contactRouter);
app.use("/api", aboutRouter);
app.use("/api", newsRouter);
app.use("/api", reviewRouter);
app.use("/api", userRouter);
app.use("/api", imageRouter);
app.use("/api", statusOrderRouter);
app.use("/api", category);
app.use("/api", products);
app.use("/api", order);
app.use("/api", dashboardRoutes);
app.use("/api", PrintInvoice);
app.use("/api", websiteInformationRoutes);
app.use("/api", paymentMethodsRoutes);
app.use("/api", statusPaymentRouters);
app.use("/api", deliveryAddressRoutes);
app.use("/api", footerRouters);

export const viteNodeApp = app;
